---
- hosts: client
  become: true
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
  vars_files:
    - files/secrets/credentials.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - odoo
